# Site settings
title: Code Bits
header-img: img/home-bg.png
email: leah.garber88@gmail.com
copyright_name: ldgarber
description: > # this means to ignore newlines until "baseurl:"
  The triumphs and struggles of learning to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ldgarber
learn_profile: ldgarber
email_username: leah.garber88@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
